### ISSUE TITLE
insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by 12bogdan03** [uniswap-python/uniswap-python#118]
Hello. 

I'm trying to use uniswap-python to execute trades on Uniswap V3. 
Here is the code:
```from uniswap import Uniswap
from web3 import Web3

provider = "https://mainnet.infura.io/v3/XXXXXXXX"
w3 = Web3(Web3.HTTPProvider(provider))

address = Web3.toChecksumAddress("XXXXXXXX")
private_key = "XXXXXXXX"
uniswap = Uniswap(address=address, private_key=private_key, version=3, provider=provider)
token = Web3.toChecksumAddress('0x85eee30c52b0b379b046fb0f85f4f3dc3009afec')
usdt = Web3.toChecksumAddress('0xdac17f958d2ee523a2206206994597c13d831ec7')

decimals_usdt = uniswap.get_token(usdt).decimals
decimals_token = uniswap.get_token(token).decimals

quantity = 10 ** decimals_token
price = uniswap.get_price_input(token, usdt, qty=quantity)
price = price / 10 ** decimals_usdt
print('price', price)

balance_usdt = uniswap.get_token_balance(usdt)
print(balance_usdt)

trade = uniswap.make_trade(usdt, token, balance_usdt)
```

And the output:
```
No fee set, assuming 0.3%
price 0.331283
91085433
Approving 0xdAC17F958D2ee523a2206206994597C13D831ec7...
Traceback (most recent call last):
  File "/Users/bohdan/PycharmProjects/binance-monitor/uni2.py", line 24, in <module>
    trade = uniswap.make_trade(usdt, token, balance_usdt)
  File "/Users/bohdan/PycharmProjects/binance-monitor/.venv/lib/python3.8/site-packages/uniswap/decorators.py", line 29, in approved
    self._approve(token)
  File "/Users/bohdan/PycharmProjects/binance-monitor/.venv/lib/python3.8/site-packages/uniswap/uniswap.py", line 852, in _approve
    tx = self._build_and_send_tx(function)
  File "/Users/bohdan/PycharmProjects/binance-monitor/.venv/lib/python3.8/site-packages/uniswap/uniswap.py", line 893, in _build_and_send_tx
    return self.w3.eth.send_raw_transaction(signed_txn.rawTransaction)
  File "/Users/bohdan/PycharmProjects/binance-monitor/.venv/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/Users/bohdan/PycharmProjects/binance-monitor/.venv/lib/python3.8/site-packages/web3/manager.py", line 160, in request_blocking
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'insufficient funds for gas * price + value'}
```

At first I thought I'm doing something wrong, so I've tried to send not all available USDT balance of my wallet, but only 80 USDT (80 * 10 ** 6 = 80000000) , but it gave mе the same ValueError  - insufficient funds for gas * price + value. 

Could you please explain what I'm doing wrong? Thanks in advance.

**Comment by ErikBjare** [comment]
Does your wallet have ETH on it?

**Comment by 12bogdan03** [comment]
Hello @ErikBjare 
Yes, the wallet didn't have ETH, that was the issue. Thanks a lot!
