### ISSUE TITLE
can't get the price of SHIBA2 coin

### ISSUE THREAD

**Issue by chiwalfrm** [uniswap-python/uniswap-python#123]
shiba2 address = 0xA0335820dC549dBfae5b8D691331CadfCA7026E0
usdc address = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

attempting to call the get_price_input function to get the SHIBA2/USDC price:

`uniswap.get_price_input('0xA0335820dC549dBfae5b8D691331CadfCA7026E0', '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48', 1000000000000000000)`

'leads to an error:

```
No route specified, assuming route: ['0xA0335820dC549dBfae5b8D691331CadfCA7026E0', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48']
Traceback (most recent call last):
  File "getuniswapprice.py", line 38, in <module>
    print(uniswap.get_price_input(address2, usdc, int(divisor))/usdcdecimals)
  File "/home/booboo/.local/lib/python3.8/site-packages/uniswap/uniswap.py", line 176, in get_price_input
    return self._get_token_token_input_price(token0, token1, qty, fee, route)
  File "/home/booboo/.local/lib/python3.8/site-packages/uniswap/uniswap.py", line 255, in _get_token_token_input_price
    price: int = self.router.functions.getAmountsOut(qty, route).call()[-1]
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/contract.py", line 954, in call
    return call_contract_function(
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/contract.py", line 1499, in call_contract_function
    return_data = web3.eth.call(call_transaction, block_identifier=block_id)
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/manager.py", line 157, in request_blocking
    apply_error_formatters(error_formatters, response)
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/manager.py", line 62, in apply_error_formatters
    formatted_response = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 544, in raise_solidity_error_on_revert
    raise ContractLogicError('execution reverted')
web3.exceptions.ContractLogicError: execution reverted
```

Why does this happen?  SHIBA2 coins have a price on Uniswap as you can see here:
https://info.uniswap.org/#/tokens/0xa0335820dc549dbfae5b8d691331cadfca7026e0

**Comment by liquid-8** [comment]
At this moment Shiba2 doesn't have direct pool with USDC but via USDT, so route for pricing/swapping is USDC->USDT->Shiba2.

There are two issues with that. First, current uniV3 implementation doesn't support multihops like that one above. Second, the route itself should be returned by optimal route function call which isn't implemented yet.

Long story short, USDT->Shiba2 works as it should and you can use it. Actual swap will convert USDC to USDT and then to SHIBA2 anyway no matter you like that or not.

**Comment by chiwalfrm** [comment]
Your reply makes it seem like I can get SHIBA2/USDT price instead by putting usdt contract address (0xdAC17F958D2ee523a2206206994597C13D831ec7) into get_price_input but it didn't work etiher:

attempting to call the get_price_input function to get the SHIBA2/USDT price:

uniswap.get_price_input('0xA0335820dC549dBfae5b8D691331CadfCA7026E0', '0xdAC17F958D2ee523a2206206994597C13D831ec7', 1000000000000000000)

Looks like the same error?

```
No route specified, assuming route: ['0xA0335820dC549dBfae5b8D691331CadfCA7026E0', '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2', '0xdAC17F958D2ee523a2206206994597C13D831ec7']
Traceback (most recent call last):
  File "getuniswappriceusdt.py", line 34, in <module>
    print(uniswap.get_price_input(address2, usdt, int(divisor))/usdtdecimals)
  File "/home/booboo/.local/lib/python3.8/site-packages/uniswap/uniswap.py", line 176, in get_price_input
    return self._get_token_token_input_price(token0, token1, qty, fee, route)
  File "/home/booboo/.local/lib/python3.8/site-packages/uniswap/uniswap.py", line 255, in _get_token_token_input_price
    price: int = self.router.functions.getAmountsOut(qty, route).call()[-1]
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/contract.py", line 954, in call
    return call_contract_function(
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/contract.py", line 1499, in call_contract_function
    return_data = web3.eth.call(call_transaction, block_identifier=block_id)
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/manager.py", line 157, in request_blocking
    apply_error_formatters(error_formatters, response)
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/manager.py", line 62, in apply_error_formatters
    formatted_response = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/home/booboo/.local/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 544, in raise_solidity_error_on_revert
    raise ContractLogicError('execution reverted')
web3.exceptions.ContractLogicError: execution reverted
```

**Comment by liquid-8** [comment]
Check next:
1. Shiba2 has pool @ uniswap v3 only
2. It has pools both eth and usdt with fee =1% only. By default get_price_input() assumes fee = 0.3% so you need to pass explicit value

**Comment by chiwalfrm** [comment]
Thank you for being patient with me, I am new at this...  First I set version = 3 to deal with the first point.

I don't really know how to deal with the second ("pass explicit value for fee").  The get_price_input only takes 3 parameters, as far as I can tell (token_address, usdt_address, quantity).  Could you show me how to call get_price_input with explicit fee to get my code working?

**Comment by chiwalfrm** [comment]
Thanks, setting the version to 3 and the fee to 1% worked!
