### ISSUE TITLE
can't get the price of token price

### ISSUE THREAD

**Issue by hzqandy123** [uniswap-python/uniswap-python#127]
provider = "https://mainnet.infura.io/v3/xxxx"
w3 = Web3(Web3.HTTPProvider(provider))

address = Web3.toChecksumAddress("xxxx")
private_key = "xxxx"
uniswap = Uniswap(address=address, private_key=private_key, version=3, provider=provider)
qnt = Web3.toChecksumAddress('0x4a220e6096b25eadb88358cb44068a3248254675')
usdt = Web3.toChecksumAddress('0xdac17f958d2ee523a2206206994597c13d831ec7')

decimals_usdt = uniswap.get_token(usdt).decimals
decimals_token = uniswap.get_token(token).decimals

quantity = 10 ** decimals_token * 50000
price = uniswap.get_price_input(usdt, qnt , qty=quantity)
price = price / 10 ** decimals_usdt
print('price', price)

'leads to an error:

Traceback (most recent call last):
  File "C:\Users\edison\Desktop\uniswap-python-3\tests\testy7.py", line 31, in <module>
    price = uniswap.get_price_input(usdt, token, qty=quantity)
  File "C:\Users\edison\Desktop\uniswap-python-3\uniswap\uniswap.py", line 176, in get_price_input
    return self._get_token_token_input_price(token0, token1, qty, fee, route)
  File "C:\Users\edison\Desktop\uniswap-python-3\uniswap\uniswap.py", line 264, in _get_token_token_input_price
    price = self.quoter.functions.quoteExactInputSingle(
  File "C:\Users\edison\Desktop\uniswap-python-3\venv\lib\site-packages\web3\contract.py", line 957, in call
    return call_contract_function(
  File "C:\Users\edison\Desktop\uniswap-python-3\venv\lib\site-packages\web3\contract.py", line 1501, in call_contract_function
    return_data = web3.eth.call(
  File "C:\Users\edison\Desktop\uniswap-python-3\venv\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "C:\Users\edison\Desktop\uniswap-python-3\venv\lib\site-packages\web3\manager.py", line 159, in request_blocking
    apply_error_formatters(error_formatters, response)
  File "C:\Users\edison\Desktop\uniswap-python-3\venv\lib\site-packages\web3\manager.py", line 63, in apply_error_formatters
    formatted_response = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
    return c_pipe(data, funcs)
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
    data = func(data)
  File "C:\Users\edison\Desktop\uniswap-python-3\venv\lib\site-packages\web3\_utils\method_formatters.py", line 544, in raise_solidity_error_on_revert
    raise ContractLogicError('execution reverted')
web3.exceptions.ContractLogicError: execution reverted

Process finished with exit code 1

Why does this happen?

**Comment by liquid-8** [comment]
There is not enough liquidity in the USDT-QNT pool to swap 50k USDT for that token so first USDT swaps for ETH and then ETH swaps for QNT. Pricing has the same route. That leads to the issue being described here https://github.com/uniswap-python/uniswap-python/issues/123

**Comment by liquid-8** [comment]
Btw I'm sure you calculate quantity wrong way bc it should be
quantity = 10 ** **decimals_usdt** * 50000
as you call get_price_input() for usdt->qnt pricing. Nevertheless, the main cause has been described above.

**Comment by hzqandy123** [comment]
3q~
