### ISSUE TITLE
make_trade error

### ISSUE THREAD

**Issue by snailAlice** [uniswap-python/uniswap-python#163]
code:
# -*- coding: UTF-8 -*-
from uniswap import Uniswap
from web3 import Web3
address = "xxx"
private_key = "xxx"
version = 2 
provider = "https://ropsten.infura.io/v3/xxx"
w3 = Web3(Web3.HTTPProvider('https://ropsten.infura.io/v3/xxx'))
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider)

eth = "0x0000000000000000000000000000000000000000"
bat = "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
dai = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
response = uniswap.make_trade(eth,dai,1*10**17)
print(response)

error:
Traceback (most recent call last):
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/web3/contract.py", line 1513, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/eth_abi/decoding.py", line 308, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/PycharmProjects/coinlist/coin_uniswap.py", line 27, in <module>
    response = uniswap.make_trade(eth,dai,1*10**17)
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/uniswap/decorators.py", line 31, in approved
    is_approved = self._is_approved(token_two)
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/uniswap/uniswap.py", line 873, in _is_approved
    .functions.allowance(self.address, contract_addr)
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/web3/contract.py", line 968, in call
    **self.kwargs
  File "/Users/.conda/envs/coinlist/lib/python3.7/site-packages/web3/contract.py", line 1530, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

The above error was reported when I used ropsten to test the network test

**Comment by liquid-8** [comment]
https://github.com/uniswap-python/uniswap-python/discussions/151

**Comment by snailAlice** [comment]
Is there a suitable contract to test on the ropsten network?
