### ISSUE TITLE
Missing library for uniswap_python package (dotenv)

### ISSUE THREAD

**Issue by MatthiasDE** [uniswap-python/uniswap-python#225]
**Describe the bug**
Fresh install on new venv with "pip install uniswap-python" and usage of unipy fails with error 

**To Reproduce**
`python -m venv .\venv`
`pip install uniswap-python`
`unipy`
`unipy price WETH DAI`

>>Error: 
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\Projects\uniswap-test.python\venv\Scripts\unipy.exe\__main__.py", line 4, in <module>
  File "H:\Projects\uniswap-test.python\venv\lib\site-packages\uniswap\__init__.py", line 3, in <module>
    from .cli import main
  File "H:\Projects\uniswap-test.python\venv\lib\site-packages\uniswap\cli.py", line 5, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

**Expected behavior**
no error and usage of unipy without missing dotenv module possible

**Additional context**
uniswap_python-0.5.4-py3-none-any.whl from pypi

**Comment by KeremP** [comment]
pip installing python-dotenv should fix for now 👍 

@ErikBjare seems python-dotenv package is set as a dev dependency in the toml file

**Comment by ErikBjare** [comment]
Fixed in https://github.com/uniswap-python/uniswap-python/commit/7ad1c178221b384f3fa1ce29a14fcb31bde275d3 and published a new version to PyPI.

Thanks for reporting!
