### ISSUE TITLE
invalid token address for eth

### ISSUE THREAD

**Issue by potuz** [uniswap-python/uniswap-python#229]
**To Reproduce**
Run the code in examples/price_impact.py

**Expected behavior**
Get the price impact of a swap eth to vxv

** Actual behaviour **
```
$ PROVIDER='http://127.0.0.1:8545' python test.py 
Impact for buying VXV on v2 with 10.0 USDT:  100%
Impact for buying VXV on v2 with 13900.0 USDT:  100%
Exception occurred while trying to get token 0x0000000000000000000000000000000000000000: Could not transact with/call contract function, is contract deployed correctly and chain synced?
Traceback (most recent call last):
  File "/path/.local/lib/python3.10/site-packages/web3/contract.py", line 1513, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/path/.local/lib/python3.10/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/path/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/path/.local/lib/python3.10/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/path/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/path/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/path/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 142, in decode
    start_pos = decode_uint_256(stream)
  File "/path/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/path/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/path/.local/lib/python3.10/site-packages/eth_abi/decoding.py", line 305, in read_data_from_stream
    raise InsufficientDataBytes(
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/.local/lib/python3.10/site-packages/uniswap/uniswap.py", line 1217, in get_token
    _name = token_contract.functions.name().call()
  File "/path/.local/lib/python3.10/site-packages/web3/contract.py", line 957, in call
    return call_contract_function(
  File "/path/.local/lib/python3.10/site-packages/web3/contract.py", line 1530, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/test.py", line 62, in <module>
    eth_to_vxv_v3()
  File "/path/test.py", line 52, in eth_to_vxv_v3
    impact = uniswap.estimate_price_impact(eth, vxv, qty, fee=10000)
  File "/path/.local/lib/python3.10/site-packages/uniswap/uniswap.py", line 1351, in estimate_price_impact
    cost_amount / (amount_in / (10 ** self.get_token(token_in).decimals))
  File "/path/.local/lib/python3.10/site-packages/uniswap/uniswap.py", line 1224, in get_token
    raise InvalidToken(address)
uniswap.exceptions.InvalidToken: Invalid token address: 0x0000000000000000000000000000000000000000
```

**Comment by potuz** [comment]
Seems like an omission in `get_token`, the following addition is a workaround to make it work in this case since eth is not a contract

```
        # FIXME: This function should always return the same output for the same input
        #        and would therefore benefit from caching
+        if address==Web3.toChecksumAddress("0x0000000000000000000000000000000000000000"):
+           return ERC20Token("eth", address, "eth", 18)
        token_contract = _load_contract(self.w3, abi_name, address=address)
        try:
            _name = token_contract.functions.name().call()
            _symbol = token_contract.functions.symbol().call()
```
