### ISSUE TITLE
ValueError: {'code': -32603, 'message': 'Remote node did not answer to eth_feeHistory correctly'}

### ISSUE THREAD

**Issue by venom-d** [uniswap-python/uniswap-python#240]
Traceback (most recent call last):
  File "/hd/honeypot.py", line 47, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/hd/honeypot.py", line 36, in main
    us.make_trade(token, eth, 100000000000000)
  File "/usr/local/lib/python3.10/site-packages/uniswap/decorators.py", line 29, in approved
    self.approve(token)
  File "/usr/local/lib/python3.10/site-packages/uniswap/uniswap.py", line 1073, in approve
    tx = self._build_and_send_tx(function)
  File "/usr/local/lib/python3.10/site-packages/uniswap/uniswap.py", line 1107, in _build_and_send_tx
    transaction = function.buildTransaction(tx_params)
  File "/usr/local/lib/python3.10/site-packages/web3/contract.py", line 1079, in buildTransaction
    return build_transaction_for_function(
  File "/usr/local/lib/python3.10/site-packages/web3/contract.py", line 1648, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(web3, prepared_transaction)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.10/site-packages/web3/_utils/transactions.py", line 114, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "/usr/local/lib/python3.10/site-packages/web3/_utils/transactions.py", line 64, in <lambda>
    web3.eth.max_priority_fee + (2 * web3.eth.get_block('latest')['baseFeePerGas'])
  File "/usr/local/lib/python3.10/site-packages/web3/eth.py", line 637, in max_priority_fee
    return fee_history_priority_fee(self)
  File "/usr/local/lib/python3.10/site-packages/web3/_utils/fee_utils.py", line 45, in fee_history_priority_fee
    fee_history = eth.fee_history(*PRIORITY_FEE_HISTORY_PARAMS)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/web3/eth.py", line 863, in fee_history
    return self._fee_history(block_count, newest_block, reward_percentiles)
  File "/usr/local/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32603, 'message': 'the method eth_feeHistory does not exist/is not available'}

**Comment by venom-d** [comment]
web3  version:   5.28.0

**Comment by ChristianCoenen** [comment]
The method `_build_and_send_tx` (a method in the underlying web3 library) is trying to query `eth_feeHistory` from ganache which is not added yet (See: https://github.com/trufflesuite/ganache/issues/1470). So when you're trying to call a smart contract with this library or the underlying web3 library on a ganache blockchain, this error occurs.

Will update here when I found a workaround.

**Comment by venom-d** [comment]
> ## Workaround
> You can prevent the error above if you provide the gas price on your own.
> 
> ```python
> _build_and_send_tx(function, tx_params={"gas_price": 10})
> ```
> 
> Since `_build_and_send_tx` is called by the methods you're likely using, you need to override either the transaction building method or the `_build_and_send_tx` method. Maybe there's another way but that's the first approaches that came to mind.

thx，we find web3 version: 5.24.0
