### ISSUE TITLE
execution reverted: PancakeLibrary: IDENTICAL_ADDRESSES

### ISSUE THREAD

**Issue by PLKuba** [uniswap-python/uniswap-python#252]
When trying to perform a swap on BSC chain, the following error occurs.

`execution reverted: PancakeLibrary: IDENTICAL_ADDRESSES`

This is the code:
```python
# specify which VERSION of Uniswap to use
VERSION = 2

# binance smart chain provider
BSC_PROVIDER = 'https://speedy-nodes-nyc.moralis.io/XXXXX/bsc/mainnet/archive'

# pancakeswap router address
PANCAKESWAP_ROUTER_CONTRACT_ADDRESS = '0x10ED43C718714eb63d5aA57B78B54704E256024E'

# pancakeswap factory contract address
PANCAKESWAP_FACTORY_CONTRACT_ADDRESS = '0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73'

bsc_busd = '0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56'
bsc_bnb = '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'

token0_amount = 0.0001
token0_decimals = 18

sender_address = ''
private_key = ''

pancakeswap = Uniswap(address=sender_address, private_key=private_key, version=VERSION,
                      router_contract_addr=PANCAKESWAP_ROUTER_CONTRACT_ADDRESS,
                      factory_contract_addr=PANCAKESWAP_FACTORY_CONTRACT_ADDRESS,
                      provider=BSC_PROVIDER)

token0 = Web3.toChecksumAddress(token0_address)
token1 = Web3.toChecksumAddress(token1_address)

pancakeswap.make_trade(token0, token1, int(token0_amount * 10**token0_decimals), slippage=0.01)
```

And this is the full Traceback:
```python
Traceback (most recent call last):
  File "PATH/dex_swaps.py", line 131, in <module>
    make_dex_trade(bsc_busd, bsc_bnb, token0_amount, token0_decimals, chain, sender_address, private_key)
  File "PATH/dex_swaps.py", line 67, in make_dex_trade
    pancakeswap.make_trade(token0, token1, int(token0_amount * 10**token0_decimals), slippage=slippage)
  File "PATH/venv/lib/python3.9/site-packages/uniswap/decorators.py", line 30, in approved
    return method(self, *args, **kwargs)
  File "PATH/venv/lib/python3.9/site-packages/uniswap/uniswap.py", line 426, in make_trade
    return self._token_to_token_swap_input(
  File "PATH/venv/lib/python3.9/site-packages/uniswap/uniswap.py", line 702, in _token_to_token_swap_input
    return self._build_and_send_tx(
  File "PATH/venv/lib/python3.9/site-packages/uniswap/uniswap.py", line 1107, in _build_and_send_tx
    transaction = function.buildTransaction(tx_params)
  File "PATH/venv/lib/python3.9/site-packages/web3/contract.py", line 1079, in buildTransaction
    return build_transaction_for_function(
  File "PATH/venv/lib/python3.9/site-packages/web3/contract.py", line 1648, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(web3, prepared_transaction)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "PATH/venv/lib/python3.9/site-packages/web3/_utils/transactions.py", line 121, in fill_transaction_defaults
    default_val = default_getter(web3, transaction)
  File "PATH/venv/lib/python3.9/site-packages/web3/_utils/transactions.py", line 67, in <lambda>
    'gas': lambda web3, tx: web3.eth.estimate_gas(tx),
  File "PATH/venv/lib/python3.9/site-packages/web3/eth.py", line 759, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "PATH/venv/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "PATH/venv/lib/python3.9/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "PATH/venv/lib/python3.9/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "PATH/venv/lib/python3.9/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "PATH/venv/lib/python3.9/site-packages/web3/_utils/method_formatters.py", line 576, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: PancakeLibrary: IDENTICAL_ADDRESSES
```

**Comment by ErikBjare** [comment]
Does this happen even if you're trying to swap other tokens? I'm guessing this is somehow caused by the involvement of BNB which might not be correctly handled as the native asset/WETH-alternative.

**Comment by PLKuba** [comment]
> Does this happen even if you're trying to swap other tokens? I'm guessing this is somehow caused by the involvement of BNB which might not be correctly handled as the native asset/WETH-alternative.

I also tried BSCPAD/CAKE, with same result.
I implemented `geth_poa_middleware` and it solved one issue, but now I'm getting the following error:
```python
ValueError: {'code': -32601, 'message': 'the method eth_feeHistory does not exist/is not available'}
```

**Comment by PLKuba** [comment]
> > Does this happen even if you're trying to swap other tokens? I'm guessing this is somehow caused by the involvement of BNB which might not be correctly handled as the native asset/WETH-alternative.
> 
> I also tried BSCPAD/CAKE, with same result. I implemented `geth_poa_middleware` and it solved one issue, but now I'm getting the following error:
> 
> ```python
> ValueError: {'code': -32601, 'message': 'the method eth_feeHistory does not exist/is not available'}
> ```

I tried doing this https://github.com/uniswap-python/uniswap-python/issues/217#issuecomment-997150635 but it didn't work.

**Comment by PLKuba** [comment]
I resolved this issue by replacing a built-in `_get_tx_params` with function provided by @ehtec

```python3
    def _get_tx_params(self, value: Wei = Wei(0), gas: Wei = None) -> TxParams:
        """Get generic transaction parameters."""
        params: TxParams = {
            "from": _addr_to_str(self.address),
            "value": value,
            "nonce": max(
                self.last_nonce,
                self.w3.eth.get_transaction_count(self.address)
            ),
        }
        if gas:
            params["gas"] = gas

        params["gasPrice"] = self.w3.eth.gas_price
        params["gas"] = Wei(250000)
        return params
```
