### ISSUE TITLE
make_trade problem(need help thx)

### ISSUE THREAD

**Issue by blurerzuo** [uniswap-python/uniswap-python#270]
Facing issue when call the make_trade function, which is:

uniswap.make_trade(eth, dai, 0.01*10**18)

result is:

Traceback (most recent call last):
  File "D:\PycharmProjects\pythonProject\swap\unipytest.py", line 30, in <module>
    uniswap.make_trade(eth, dai, 0.01*10**18)
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\uniswap\decorators.py", line 30, in approved
    return method(self, *args, **kwargs)
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\uniswap\uniswap.py", line 418, in make_trade
    return self._eth_to_token_swap_input(
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\uniswap\uniswap.py", line 507, in _eth_to_token_swap_input
    (1 - slippage) * self._get_eth_token_input_price(output_token, qty, fee)
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\uniswap\uniswap.py", line 232, in _get_eth_token_input_price
    price = self.router.functions.getAmountsOut(
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\web3\contract.py", line 878, in __call__
    clone._set_function_info()
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\web3\contract.py", line 883, in _set_function_info
    self.abi = find_matching_fn_abi(
  File "D:\PycharmProjects\pythonProject\venv\lib\site-packages\web3\_utils\contracts.py", line 163, in find_matching_fn_abi
    raise ValidationError(message)
web3.exceptions.ValidationError: 
Could not identify the intended function with name `getAmountsOut`, positional argument(s) of type `(<class 'float'>, <class 'list'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `getAmountsOut`: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.

**Comment by blurerzuo** [comment]
qty can not be  0.01*10**18

**Comment by ErikBjare** [comment]
Yeah, because the amount needs to be an integer. If you'd searched the issues you'd have found others making the same mistake. 

We could raise a clearer error here, though. But if you'd have uses a type-checking tool like mypy (you should), then it would have told you the issue straight away.
