### ISSUE TITLE
polygon/uniswapV3: web3.exceptions.ValidationError: Could not identify the intended function with name `quoteExactInputSingle`

### ISSUE THREAD

**Issue by snarflakes** [uniswap-python/uniswap-python#284]
Trying to make a trade using polygon uniswapv3

CODE:

from uniswap import Uniswap
from web3.middleware import geth_poa_middleware

infura_url = 'https://polygon-mainnet.infura.io/v3/XXXXXXXXXXXXXX

w3 = Web3(Web3.HTTPProvider(infura_url))

w3.middleware_onion.inject(geth_poa_middleware, layer=0)

address = "xxxxxxxxxxxxxxxxxd"          # or None if you're not going to make transactions
private_key = "xxxxxxxxxxxx" #private_key = "YOUR PRIVATE KEY"  # or None if you're not going to make transactions
version = 3                       # specify which version of Uniswap to use
provider = "https://polygon-mainnet.infura.io/v3/xxxxxxxxxxxxxxxx"    # can also be set through the environment variable `PROVIDER`

uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider, web3=w3)

#Some token addresses we'll be using later in this guide
#eth = "0x0000000000000000000000000000000000000000"
#bat = "0x0D8775F648430679A709E98d2b0Cb6250d2887EF"
#dai = "0x6B175474E89094C44Da98b954EedeAC495271d0F"
usdc = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
weth = "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
wmatic = "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"

tx_hash = uniswap.make_trade(usdc, weth, .1*10**6, fee=500)

__________________________________________________________________________________________________________
Traceback (most recent call last):
  File "c:\Users\rtringal\Desktop\codeplaygorund\testnetUSDCtoETH - using pythonuniswap module - polygon.py", line 133, in <module>
    tx_hash = uniswap.make_trade(usdc, weth, .1*10**6, fee=500)
  File "C:\Users\rtringal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uniswap\decorators.py", line 38, in approved
    return method(self, *args, **kwargs)
  File "C:\Users\rtringal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uniswap\uniswap.py", line 468, in make_trade
    return self._token_to_token_swap_input(
  File "C:\Users\rtringal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uniswap\uniswap.py", line 758, in _token_to_token_swap_input
    * self._get_token_token_input_price(
  File "C:\Users\rtringal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\uniswap\uniswap.py", line 333, in _get_token_token_input_price
    price = self.quoter.functions.quoteExactInputSingle(
  File "C:\Users\rtringal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\contract.py", line 891, in __call__
    clone._set_function_info()
  File "C:\Users\rtringal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\contract.py", line 896, in _set_function_info
    self.abi = find_matching_fn_abi(
  File "C:\Users\rtringal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\_utils\contracts.py", line 163, in find_matching_fn_abi
    raise ValidationError(message)
web3.exceptions.ValidationError:
Could not identify the intended function with name `quoteExactInputSingle`, positional argument(s) of type `(<class 'str'>, <class 'str'>, <class 'int'>, <class 'float'>, <class 'int'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `quoteExactInputSingle`: ['quoteExactInputSingle(address,address,uint24,uint256,uint160)']
Function invocation failed due to no matching argument types.

**Expected behavior**
simple swap on polygon uniswap v3

**Comment by KeremP** [comment]
`qty` in `make_trade()` should be an int or of web3 type Wei looks like you're passing a float

**Comment by snarflakes** [comment]
Thanks I will try that and let you know!

**Comment by snarflakes** [comment]
Yup that fixed it thanks!

**Comment by ErikBjare** [comment]
I've noticed a lot of people are bumping into this issue, so I've added some type-validation to give a more descriptive error message in 05f6976.
