### ISSUE TITLE
uniswapV3,goerli: AttributeError: 'multicall' object has no attribute 'build_transaction'. Did you mean: 'buildTransaction'?

### ISSUE THREAD

**Issue by snarflakes** [uniswap-python/uniswap-python#285]
**Describe the bug**
Strange. This is code for vanilla v3 uniswap goerli testnet transaction that worked twice in succession (USDC approvals had already been done with that account previously) and then days later (same wallet address/but running same code from different computer) started to fail with this error everytime. I've tried to run it on brand new addresses and it still gives the same error. Any ideas? It looks like it is getting hung up in approvals? I'm stumped.

code:

from web3 import Web3
import json
import requests 
import time
from uniswap import Uniswap

address = "0xXXXXXXXXXXX7"
private_key = "x8bXXXXXXXXXXXXXXXXXXXX"
version = 3                       # specify which version of Uniswap to use
provider = "https://goerli.infura.io/v3/XXXXXXXXXXXXXXXXX"    # can also be set through the environment variable `PROVIDER`
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider)

eth = "0x0000000000000000000000000000000000000000"
#goerli USDC
token_address = '0x07865c6E87B9F70255377e024ace6630C1Eaa37F'
tx_hash = uniswap.make_trade(token_address, eth, 1*10**6, fee=500)
print(web3.toHex(tx_hash))

**To Reproduce**

Traceback (most recent call last):
  File "c:\Users\rolan\OneDrive\Desktop\testnetUSDCtoETH - using pythonuniswap module.py", line 123, in <module>
    tx_hash = uniswap.make_trade(token_address, eth, 1*10**8, fee=500)
  File "C:\Users\rolan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uniswap\decorators.py", line 38, in approved
    return method(self, *args, **kwargs)
  File "C:\Users\rolan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uniswap\uniswap.py", line 464, in make_trade
    return self._token_to_eth_swap_input(
  File "C:\Users\rolan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uniswap\uniswap.py", line 680, in _token_to_eth_swap_input
    return self._build_and_send_tx(
  File "C:\Users\rolan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\uniswap\uniswap.py", line 1435, in _build_and_send_tx
    transaction = function.build_transaction(tx_params)
AttributeError: 'multicall' object has no attribute 'build_transaction'. Did you mean: 'buildTransaction'?

I ran it in a slightly different context in a linux CLI environment and the error is a little different

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/pins/rpigpio.py", line 223, in _call_when_changed
    super(RPiGPIOPin, self)._call_when_changed()
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/pins/local.py", line 130, in _call_when_changed
    self.state if state is None else state)
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/pins/pi.py", line 298, in _call_when_changed
    method(ticks, state)
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/input_devices.py", line 182, in _pin_changed
    self._fire_events(ticks, bool(self._state_to_value(state)))
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/mixins.py", line 401, in _fire_events
    self._fire_activated()
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/mixins.py", line 447, in _fire_activated
    super(HoldMixin, self)._fire_activated()
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/mixins.py", line 364, in _fire_activated
    self.when_activated()
  File "image.py", line 322, in push_button
    transactions()
  File "image.py", line 457, in transactions
    tx_hash = uniswap.make_trade(token_address, eth, 1*10**8, fee=500)
  File "/usr/local/lib/python3.7/dist-packages/uniswap/decorators.py", line 37, in approved
    self.approve(token)
  File "/usr/local/lib/python3.7/dist-packages/uniswap/uniswap.py", line 1401, in approve
    tx = self._build_and_send_tx(function)
  File "/usr/local/lib/python3.7/dist-packages/uniswap/uniswap.py", line 1435, in _build_and_send_tx
    transaction = function.build_transaction(tx_params)
AttributeError: 'approve' object has no attribute 'build_transaction'

**Expected behavior**
transaction to go through like it did the first time.
this one went through successfully: https://goerli.etherscan.io/tx/0x134af03982544048f52649cdff5676a200dcf23439f1191781ee79fd3a47bdf8

After trying exact same code on home computer, went back to original work computer and they went through normally!
https://goerli.etherscan.io/tx/0x10849d8b6da7cca7b76ec5938eba22b6f99d570c77c0a3b0af9aed843d020a2f

**Comment by snarflakes** [comment]
Solved.  Working computer had the newer version of module "web3."  It didn't work on the computers with the older version of web3.
