### ISSUE TITLE
Exception: Unknown netid: 80001

### ISSUE THREAD

**Issue by philmoreau** [uniswap-python/uniswap-python#314]
After installing either through pip or git, and running the simple code in the "Getting Started" page of the doc, I get : 

```
Traceback (most recent call last):
  File "/app/main.py", line 29, in <module>
    main()
  File "/app/main.py", line 16, in main
    uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider)
  File "/usr/local/lib/python3.9/site-packages/uniswap/uniswap.py", line 128, in __init__
    raise Exception(f"Unknown netid: {self.netid}")  # pragma: no cover
Exception: Unknown netid: 80001
```

**Comment by ErikBjare** [comment]
Are you using a Polygon testnet RPC? (a brief search suggested so)

You need to add the appropriate network here: https://github.com/uniswap-python/uniswap-python/blob/master/uniswap/constants.py

**Comment by philmoreau** [comment]
I see. Thanks for pointing me in the right direction! I'll try to figure out how this works.

Amazing reply time by the way.

**Comment by koots1234** [comment]
I'm also having this same error, using Sepolia Testnet, I've checked constants.py and its listed in _netid_to_name. Any suggestions?
