### ISSUE TITLE
unable to swap

### ISSUE THREAD

**Issue by nithesh10** [uniswap-python/uniswap-python#341]
please help me solve, tried swap aswell as get_price_input , but it fails, what version of web3 are you using ?

bal=get_token_balance(w3,wasfb,public_key)
print(bal)
dec=get_token_decimals(w3,wasfb)
print("decimal is",dec)
print(double(bal/10**dec))
balance=double(bal/10**dec)
balance=double(balance/2)
print("balance is",balance)
uniswap = Uniswap(address=public_key, private_key=private_key, version=3,web3=w3,default_slippage=5)
eth_balance=uniswap.get_eth_balance()
print("eth balance",eth_balance)
print(uniswap.get_token_balance(wasfb))
a=uniswap.get_price_input(ETH_ADDRESS,wasfb,(int(eth_balance/2)))
print(a)

0
decimal of wasfb is 9
0.0
balance is 0.0
eth balance 100000000000000000
0
No fee set, assuming 0.3%
Traceback (most recent call last):
  File "f:\a.nithesh_clients\rff\volume\test.py", line 65, in <module>
    a=uniswap.get_price_input(ETH_ADDRESS,wasfb,(int(eth_balance/2)))
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\uniswap\uniswap.py", line 232, in get_price_input
    return self._get_eth_token_input_price(token1, Wei(qty), fee)
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\uniswap\uniswap.py", line 274, in _get_eth_token_input_price
    price = self._get_token_token_input_price(
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\uniswap\uniswap.py", line 340, in _get_token_token_input_price
    ).call()
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\contract\contract.py", line 283, in call
    return call_contract_function(
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\contract\utils.py", line 96, in call_contract_function
    return_data = w3.eth.call(
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\eth\eth.py", line 256, in call
    return self._durin_call(transaction, block_identifier, state_override)
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\eth\eth.py", line 275, in _durin_call
    return self._call(transaction, block_identifier, state_override)
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\module.py", line 68, in caller
    result = w3.manager.request_blocking(
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\manager.py", line 232, in request_blocking
    return self.formatted_response(
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\manager.py", line 197, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\manager.py", line 72, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz\functoolz.pyx", line 666, in cytoolz.functoolz.pipe
  File "cytoolz\functoolz.pyx", line 641, in cytoolz.functoolz.c_pipe
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\_utils\contract_error_handling.py", line 135, in raise_contract_logic_error_on_revert

    raise ContractLogicError("execution reverted", data=data)
web3.exceptions.ContractLogicError: execution reverted
PS F:\a.nithesh_clients\rff\volume>

**Comment by nithesh10** [comment]
works on usdt, but not working on custom tokens

**Comment by nithesh10** [comment]
works on v2, but not on v3

**Comment by nithesh10** [comment]
How to fix this , getting this on v2

exception:- 
Could not identify the intended function with name `swapExactETHForTokens`, positional arguments with type(s) `int,(address,address),int,int` and keyword arguments with type(s) `{}`.
Found 1 function(s) with the name `swapExactETHForTokens`: ['swapExactETHForTokens(uint256,address[],address,uint256)']
Function invocation failed due to no matching argument types.

**Comment by nithesh10** [comment]
def swap(self,public_key,private_key,from_address,to_address,amount,slippage,chain):
        slippage=int(slippage)
        public_key=self.w3.to_checksum_address(public_key)
        uniswap = Uniswap(address=public_key, private_key=private_key, version=2,web3=self.w3,default_slippage=slippage)
        print("amount is",amount)
        #a=uniswap.get_price_input(from_address,to_address,int(amount))
        a=uniswap.make_trade(from_address,to_address,int(amount/2),public_key,fee=10000)
        tx = uniswap.w3.eth.wait_for_transaction_receipt(a, timeout=5)
        return tx


Could not identify the intended function with name `swapExactETHForTokens`, positional arguments with type(s) `int,(address,address),address,int` and keyword arguments with type(s) `{}`.
Found 1 function(s) with the name `swapExactETHForTokens`: ['swapExactETHForTokens(uint256,address[],address,uint256)']

**Comment by nithesh10** [comment]
please respond

**Comment by nithesh10** [comment]
was a slippage issue, fixed it

but now im getting this error when i swap from the token to eth

Traceback (most recent call last):
  File "f:\a.nithesh_clients\rff\volume\test.py", line 66, in <module>
    a=uniswap.make_trade(wasfb,ETH_ADDRESS,(int(token_balance)))
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\uniswap\decorators.py", line 38, in approved
    return method(self, *args, **kwargs)
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\uniswap\uniswap.py", line 472, in make_trade
    return self._token_to_eth_swap_input(
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\uniswap\uniswap.py", line 644, in _token_to_eth_swap_input
    return self._build_and_send_tx(
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\uniswap\uniswap.py", line 1443, in _build_and_send_tx
    transaction = function.build_transaction(tx_params)
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\contract\contract.py", line 332, in build_transaction
    return build_transaction_for_function(
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\contract\utils.py", line 232, in build_transaction_for_function
    prepared_transaction = fill_transaction_defaults(w3, prepared_transaction)
  File "cytoolz\functoolz.pyx", line 249, in cytoolz.functoolz.curry.__call__
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\_utils\transactions.py", line 132, in fill_transaction_defaults
    default_val = default_getter(w3, transaction)
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\_utils\transactions.py", line 72, in <lambda>
    "gas": lambda w3, tx: w3.eth.estimate_gas(tx),
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\eth\eth.py", line 293, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\module.py", line 68, in caller
    result = w3.manager.request_blocking(
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\manager.py", line 232, in request_blocking
    return self.formatted_response(
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\manager.py", line 197, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\manager.py", line 72, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz\functoolz.pyx", line 666, in cytoolz.functoolz.pipe
  File "cytoolz\functoolz.pyx", line 641, in cytoolz.functoolz.c_pipe
  File "C:\Users\anith\AppData\Roaming\Python\Python310\site-packages\web3\_utils\contract_error_handling.py", line 131, in raise_contract_logic_error_on_revert

    raise ContractLogicError(message, data=data)
web3.exceptions.ContractLogicError: execution reverted: UniswapV2: K

**Comment by nithesh10** [comment]
fixed it with set fee to true
