### ISSUE TITLE
Website says can use this library on Sushiswap and others, and to look at Issues on how to do it. But could not find it. How to connect to Sushiswap instead of Uniswap?

### ISSUE THREAD

**Issue by nomadph888** [uniswap-python/uniswap-python#401]
I could not find under Issues how to use uniswap-python to swap on Sushiswap, please help me how to do it?

Also, is it possible to simultaneously create two instance of uniswap in a Python project, one connects to Uniswap, and the other to Sushiswap? I am going to use Polygon network if it matters. I already have made infura account & API key.

Thank you.

**Comment by liquid-8** [comment]
>I could not find under Issues how to use uniswap-python to swap on Sushiswap, please help me how to do it?

```
from uniswap import Uniswap

address = "YOUR ADDRESS"          # or None if you're not going to make transactions
private_key = "YOUR PRIVATE KEY"  # or None if you're not going to make transactions
version = 2                       # specify which version of Uniswap to use
provider = "WEB3 PROVIDER URL"    # can also be set through the environment variable `PROVIDER`
router_contract_addr = sushiswap_router_addr
factory_contract_addr= sushiswap_factory_addr
uniswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider, router_contract_addr = router_contract_addr, factory_contract_addr = factory_contract_addr)
```
>is it possible to simultaneously create two instance of uniswap in a Python project, one connects to Uniswap, and the other to Sushiswap?

Yes, as many as you need.

**Comment by nomadph888** [comment]
Hello, I did as you said:

```
address = None
private_key = None
version = 2
provider = "https://polygon-rpc.com/"
router_contract_addr = Web3.to_checksum_address("0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506")
factory_contract_addr= Web3.to_checksum_address("0xc35DADB65012eC5796536bD9864eD8773aBc74C4")
sushiswap = Uniswap(address=address, private_key=private_key, version=version, provider=provider, default_slippage=0.002, router_contract_addr = router_contract_addr, factory_contract_addr = factory_contract_addr)

usdc = Web3.to_checksum_address("0x3c499c542cef5e3811e1192ce70d8cc03d5c3359")
eure = Web3.to_checksum_address("0x18ec0a6e18e5bc3784fdd3a3634b31245ab704f6")

hello = sushiswap.get_price_input(usdc, eure, 10**6, fee=500)
hello = hello / 10**18

print(hello)
```

but I get this error:

```
No route specified, assuming route: ['0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359', '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270', '0x18ec0A6E18E5bc3784fDd3a3634b31245ab704F6']
Traceback (most recent call last):
  File "C:\Users\willi\Desktop\uniswap\uniswap_sample.txt", line 32, in <module>
    hello = sushiswap.get_price_input(usdc, eure, 10**6, fee=500)
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\uniswap\uniswap.py", line 247, in get_price_input
    return self._get_token_token_input_price(token0, token1, qty, fee, route)
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\uniswap\uniswap.py", line 340, in _get_token_token_input_price
    price: int = self.router.functions.getAmountsOut(qty, route).call()[-1]
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\web3\contract\contract.py", line 305, in call
    return call_contract_function(
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\web3\contract\utils.py", line 96, in call_contract_function
    return_data = w3.eth.call(
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\web3\eth\eth.py", line 260, in call
    return self._durin_call(transaction, block_identifier, state_override)
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\web3\eth\eth.py", line 279, in _durin_call
    return self._call(transaction, block_identifier, state_override)
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\web3\module.py", line 75, in caller
    result = w3.manager.request_blocking(
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\web3\manager.py", line 330, in request_blocking
    return self.formatted_response(
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\web3\manager.py", line 291, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\web3\manager.py", line 104, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz\\functoolz.pyx", line 680, in cytoolz.functoolz.pipe
  File "cytoolz\\functoolz.pyx", line 655, in cytoolz.functoolz.c_pipe
  File "C:\Users\willi\AppData\Roaming\Python\Python39\site-packages\web3\_utils\error_formatters_utils.py", line 165, in raise_contract_logic_error_on_revert
    raise ContractLogicError("execution reverted", data=data)
web3.exceptions.ContractLogicError: ('execution reverted', 'no data')
```

any ideas? I want to do is get price from sushiswap (and uniswap eventually) of specific tokens or coins for possible swapping as an exercise to learn.
