### ISSUE TITLE
Failed to build installable wheels for some pyproject.toml based projects (ckzg)

### ISSUE THREAD

**Issue by chlenc** [uniswap-python/uniswap-python#409]
**Describe the bug**
Hi guys, I'm trying to install the package and faced into a problem Failed to build installable wheels for some pyproject.toml based projects (ckzg)

**To Reproduce**
```
pip install uniswap-python   
```
**Expected behavior**
The package should be installed

**Additional context**
```
pip install uniswap-python                                                                                                                                                                                       (*master+6) 13:10:39 
Collecting uniswap-python
  Using cached uniswap_python-0.7.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: click<9.0.0,>=8.0.3 in ./venv/lib/python3.13/site-packages (from uniswap-python) (8.1.7)
Requirement already satisfied: python-dotenv in ./venv/lib/python3.13/site-packages (from uniswap-python) (1.0.1)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.13/site-packages (from uniswap-python) (4.12.2)
Collecting web3<7.0,>=6.0 (from uniswap-python)
  Using cached web3-6.20.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: aiohttp>=3.7.4.post0 in ./venv/lib/python3.13/site-packages (from web3<7.0,>=6.0->uniswap-python) (3.10.10)
Collecting ckzg<2 (from web3<7.0,>=6.0->uniswap-python)
  Using cached ckzg-1.0.2.tar.gz (840 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting eth-abi>=4.0.0 (from web3<7.0,>=6.0->uniswap-python)
  Using cached eth_abi-5.1.0-py3-none-any.whl.metadata (5.1 kB)
Collecting eth-account<0.13,>=0.8.0 (from web3<7.0,>=6.0->uniswap-python)
  Using cached eth_account-0.12.4-py3-none-any.whl.metadata (5.1 kB)
Collecting eth-hash>=0.5.1 (from eth-hash[pycryptodome]>=0.5.1->web3<7.0,>=6.0->uniswap-python)
  Using cached eth_hash-0.7.0-py3-none-any.whl.metadata (5.4 kB)
Collecting eth-typing!=4.2.0,<5.0.0,>=3.0.0 (from web3<7.0,>=6.0->uniswap-python)
  Using cached eth_typing-4.4.0-py3-none-any.whl.metadata (5.1 kB)
Collecting eth-utils<5,>=2.1.0 (from web3<7.0,>=6.0->uniswap-python)
  Using cached eth_utils-4.1.1-py3-none-any.whl.metadata (5.4 kB)
Collecting hexbytes<0.4.0,>=0.1.0 (from web3<7.0,>=6.0->uniswap-python)
  Using cached hexbytes-0.3.1-py3-none-any.whl.metadata (5.5 kB)
Collecting jsonschema>=4.0.0 (from web3<7.0,>=6.0->uniswap-python)
  Using cached jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting lru-dict<1.3.0,>=1.1.6 (from web3<7.0,>=6.0->uniswap-python)
  Using cached lru_dict-1.2.0-cp313-cp313-macosx_12_0_arm64.whl
Requirement already satisfied: protobuf>=4.21.6 in ./venv/lib/python3.13/site-packages (from web3<7.0,>=6.0->uniswap-python) (5.29.0rc2)
Requirement already satisfied: requests>=2.16.0 in ./venv/lib/python3.13/site-packages (from web3<7.0,>=6.0->uniswap-python) (2.32.3)
Collecting websockets>=10.0.0 (from web3<7.0,>=6.0->uniswap-python)
  Using cached websockets-13.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.8 kB)
Collecting pyunormalize>=15.0.0 (from web3<7.0,>=6.0->uniswap-python)
  Using cached pyunormalize-16.0.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in ./venv/lib/python3.13/site-packages (from aiohttp>=3.7.4.post0->web3<7.0,>=6.0->uniswap-python) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.13/site-packages (from aiohttp>=3.7.4.post0->web3<7.0,>=6.0->uniswap-python) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.13/site-packages (from aiohttp>=3.7.4.post0->web3<7.0,>=6.0->uniswap-python) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.13/site-packages (from aiohttp>=3.7.4.post0->web3<7.0,>=6.0->uniswap-python) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.13/site-packages (from aiohttp>=3.7.4.post0->web3<7.0,>=6.0->uniswap-python) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in ./venv/lib/python3.13/site-packages (from aiohttp>=3.7.4.post0->web3<7.0,>=6.0->uniswap-python) (1.17.1)
Collecting parsimonious<0.11.0,>=0.10.0 (from eth-abi>=4.0.0->web3<7.0,>=6.0->uniswap-python)
  Using cached parsimonious-0.10.0-py3-none-any.whl.metadata (25 kB)
Collecting bitarray>=2.4.0 (from eth-account<0.13,>=0.8.0->web3<7.0,>=6.0->uniswap-python)
  Using cached bitarray-3.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (32 kB)
Collecting eth-keyfile>=0.6.0 (from eth-account<0.13,>=0.8.0->web3<7.0,>=6.0->uniswap-python)
  Using cached eth_keyfile-0.8.1-py3-none-any.whl.metadata (8.5 kB)
Collecting eth-keys>=0.4.0 (from eth-account<0.13,>=0.8.0->web3<7.0,>=6.0->uniswap-python)
  Using cached eth_keys-0.6.0-py3-none-any.whl.metadata (13 kB)
Collecting eth-rlp>=2.1.0 (from eth-account<0.13,>=0.8.0->web3<7.0,>=6.0->uniswap-python)
  Using cached eth_rlp-2.1.0-py3-none-any.whl.metadata (4.6 kB)
INFO: pip is looking at multiple versions of eth-account to determine which version is compatible with other requirements. This could take a while.
Collecting eth-account<0.13,>=0.8.0 (from web3<7.0,>=6.0->uniswap-python)
  Using cached eth_account-0.12.3-py3-none-any.whl.metadata (5.1 kB)
  Using cached eth_account-0.12.2-py3-none-any.whl.metadata (5.1 kB)
  Using cached eth_account-0.12.1-py3-none-any.whl.metadata (5.1 kB)
  Using cached eth_account-0.12.0-py3-none-any.whl.metadata (5.1 kB)
  Using cached eth_account-0.11.3-py3-none-any.whl.metadata (5.1 kB)
Collecting rlp>=1.0.0 (from eth-account<0.13,>=0.8.0->web3<7.0,>=6.0->uniswap-python)
  Using cached rlp-4.0.1-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in ./venv/lib/python3.13/site-packages (from eth-hash[pycryptodome]>=0.5.1->web3<7.0,>=6.0->uniswap-python) (3.21.0)
Collecting cytoolz>=0.10.1 (from eth-utils<5,>=2.1.0->web3<7.0,>=6.0->uniswap-python)
  Using cached cytoolz-1.0.0-cp313-cp313-macosx_12_0_arm64.whl
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.0.0->web3<7.0,>=6.0->uniswap-python)
  Using cached jsonschema_specifications-2024.10.1-py3-none-any.whl.metadata (3.0 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.0.0->web3<7.0,>=6.0->uniswap-python)
  Using cached referencing-0.35.1-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.7.1 (from jsonschema>=4.0.0->web3<7.0,>=6.0->uniswap-python)
  Using cached rpds_py-0.20.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (4.2 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.13/site-packages (from requests>=2.16.0->web3<7.0,>=6.0->uniswap-python) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.13/site-packages (from requests>=2.16.0->web3<7.0,>=6.0->uniswap-python) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.13/site-packages (from requests>=2.16.0->web3<7.0,>=6.0->uniswap-python) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.13/site-packages (from requests>=2.16.0->web3<7.0,>=6.0->uniswap-python) (2024.8.30)
Collecting toolz>=0.8.0 (from cytoolz>=0.10.1->eth-utils<5,>=2.1.0->web3<7.0,>=6.0->uniswap-python)
  Using cached toolz-1.0.0-py3-none-any.whl.metadata (5.1 kB)
INFO: pip is looking at multiple versions of eth-rlp to determine which version is compatible with other requirements. This could take a while.
Collecting eth-rlp>=0.3.0 (from eth-account<0.13,>=0.8.0->web3<7.0,>=6.0->uniswap-python)
  Using cached eth_rlp-2.0.0-py3-none-any.whl.metadata (4.6 kB)
  Using cached eth_rlp-1.0.1-py3-none-any.whl.metadata (4.5 kB)
Collecting regex>=2022.3.15 (from parsimonious<0.11.0,>=0.10.0->eth-abi>=4.0.0->web3<7.0,>=6.0->uniswap-python)
  Using cached regex-2024.9.11-cp313-cp313-macosx_11_0_arm64.whl.metadata (40 kB)
Requirement already satisfied: propcache>=0.2.0 in ./venv/lib/python3.13/site-packages (from yarl<2.0,>=1.12.0->aiohttp>=3.7.4.post0->web3<7.0,>=6.0->uniswap-python) (0.2.0)
Using cached uniswap_python-0.7.1-py3-none-any.whl (38 kB)
Using cached web3-6.20.3-py3-none-any.whl (1.6 MB)
Using cached eth_abi-5.1.0-py3-none-any.whl (29 kB)
Using cached eth_account-0.11.3-py3-none-any.whl (355 kB)
Using cached eth_hash-0.7.0-py3-none-any.whl (8.7 kB)
Using cached eth_typing-4.4.0-py3-none-any.whl (19 kB)
Using cached eth_utils-4.1.1-py3-none-any.whl (96 kB)
Using cached hexbytes-0.3.1-py3-none-any.whl (5.9 kB)
Using cached jsonschema-4.23.0-py3-none-any.whl (88 kB)
Using cached pyunormalize-16.0.0-py3-none-any.whl (49 kB)
Using cached websockets-13.1-cp313-cp313-macosx_11_0_arm64.whl (155 kB)
Using cached bitarray-3.0.0-cp313-cp313-macosx_11_0_arm64.whl (121 kB)
Using cached eth_keyfile-0.8.1-py3-none-any.whl (7.5 kB)
Using cached eth_keys-0.6.0-py3-none-any.whl (21 kB)
Using cached eth_rlp-1.0.1-py3-none-any.whl (4.9 kB)
Using cached jsonschema_specifications-2024.10.1-py3-none-any.whl (18 kB)
Using cached parsimonious-0.10.0-py3-none-any.whl (48 kB)
Using cached referencing-0.35.1-py3-none-any.whl (26 kB)
Using cached rlp-4.0.1-py3-none-any.whl (20 kB)
Using cached rpds_py-0.20.1-cp313-cp313-macosx_11_0_arm64.whl (320 kB)
Using cached regex-2024.9.11-cp313-cp313-macosx_11_0_arm64.whl (284 kB)
Using cached toolz-1.0.0-py3-none-any.whl (56 kB)
Building wheels for collected packages: ckzg
  Building wheel for ckzg (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for ckzg (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      running bdist_wheel
      running build
      running build_ext
      + cc -O2 -fno-builtin -fPIC -Wall -Wextra -Werror -D__BLST_PORTABLE__ -c ./src/server.c
      In file included from ./src/server.c:7:
      In file included from ./src/keygen.c:7:
      In file included from ./src/consts.h:8:
      ./src/vect.h:402:11: fatal error: 'stdlib.h' file not found
      # include <stdlib.h>
                ^~~~~~~~~~
      1 error generated.
      make: *** [../lib/libblst.a] Error 1
      Traceback (most recent call last):
        File "/Users/alexey/Desktop/kassiopea-py/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/alexey/Desktop/kassiopea-py/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/alexey/Desktop/kassiopea-py/venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                              metadata_directory)
                                              ^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 437, in build_wheel
          return _build(['bdist_wheel', '--dist-info-dir', str(metadata_directory)])
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 425, in _build
          return self._build_with_temp_dir(
                 ~~~~~~~~~~~~~~~~~~~~~~~~~^
              cmd,
              ^^^^
          ...<3 lines>...
              self._arbitrary_args(config_settings),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          )
          ^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 406, in _build_with_temp_dir
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 51, in <module>
        File "<string>", line 25, in main
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/command/bdist_wheel.py", line 410, in run
          self.run_command("build")
          ~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
          ~~~~~~~~~~~~~~~~^^^^^^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/private/var/folders/3b/9szz5ktd0l57wblc74mq9mj80000gn/T/pip-build-env-erdf451b/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "<string>", line 16, in run
        File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/subprocess.py", line 419, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['make', '-C', 'src', 'blst']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ckzg
Failed to build ckzg
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ckzg)
```

**Comment by ErikBjare** [comment]
Claude correctly diagnoses the issue: 

> Looking at the error message, the key issue appears to be a missing C compiler toolchain. The specific error is:
> 
> ```
> ./src/vect.h:402:11: fatal error: 'stdlib.h' file not found
> ```
> 
> This indicates that the basic C development headers are missing. On macOS, these are typically provided by the Xcode Command Line Tools.
> </thinking>
> 
> You need to install the Xcode Command Line Tools. Let's verify if they're installed:
> 
> ```shell
> xcode-select -p
> ```

**Comment by chlenc** [comment]
xcode-select -p          

/Library/Developer/CommandLineTools
